service:
  name: aws-lambda-get-products
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  first:
    handler: src/first.hello
  second:
    handler: src/second.hello
    events:
      - httpApi:
          method: get
          path: /second
